Vagrant.configure("2") do |config|

  # script for machine-1 
  $script1 = <<-SCRIPT
      apt-get update
      apt-get install -y docker.io
      curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.17.0/bin/linux/amd64/kubectl
      chmod +x ./kubectl
      sudo mv ./kubectl /usr/local/bin/kubectl
      kubectl version --client
      curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64 \
      && sudo install minikube-linux-amd64 /usr/local/bin/minikube
      minikube start --kubernetes-version 1.17.0 --vm-driver none

  SCRIPT

   # script for machine-2 
   $script2 = <<-SCRIPT
   apt-get update
   apt-get install -y docker.io
   curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.17.0/bin/linux/amd64/kubectl
   chmod +x ./kubectl
   sudo mv ./kubectl /usr/local/bin/kubectl
   kubectl version --client
   curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64 \
   && sudo install minikube-linux-amd64 /usr/local/bin/minikube

SCRIPT

  # ubuntu machine
  config.vm.define "ubuntu" do |ubuntu|
   ubuntu.vm.box = "generic/ubuntu1804"
   ubuntu.vm.network :private_network, ip: "192.168.27.100"
   ubuntu.vm.box_check_update = false
   ubuntu.vm.hostname = "machine1"
  #  ubuntu.vm.network "forwarded_port", guest: 80, host: 8080
   ubuntu.vm.provision "shell", inline: $script1
   ubuntu.vm.provider "hyperv" do |v| # https://www.vagrantup.com/docs/virtualbox/configuration.html
    v.memory = 1024
    v.cpus = 2
    end
  end

  # debian machine
  config.vm.define "debian" do |debian|
    debian.vm.box = "debian/jessie64"
    debian.vm.network :private_network, ip: "192.168.27.101"
    debian.vm.box_check_update = false
    debian.vm.hostname = "debian"
    ubuntu.vm.provision "shell", inline: $script2
    debian.vm.provider "hyperv" do |v|
      v.memory = 1024
      v.cpus = 1
      end
  end
end
