<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Chat.aspx.cs" Inherits="NoDB.Login" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <link rel="stylesheet" type="text/css" href="Chat.css" media="screen" />
    <link rel="stylesheet" type="text/css" href="bootstrap-theme.min.css" media="screen" />
    <link rel="stylesheet" type="text/css" href="bootstrap.min.css" media="screen" />
    <script src="bootstrap.min.js" type="text/javascript"></script>
    <script src="jQuery.min.js" type="text/javascript"></script>
    <script src="myScript.js" type="text/javascript"></script>
    <title>Chat</title>
</head>
<body>
    <form id="chat" runat="server">
        <!-- container -->
        <div class="container">
            <!-- second row - Messages + Users -->
            <div class="row">
                <div id="divMessages" class="col-sm-9 messages" runat="server">
                    <asp:ListBox ID="Messages" runat="server"></asp:ListBox>
                    <!-- content generated by C# code -->
                </div>
                <div class="col-sm-3 users">
                    <asp:ListBox ID="Users" runat="server"></asp:ListBox>
                    <!-- content generated by C# code -->
                </div>
            </div><!-- second row - Messages + Users -->
            
            <!-- third row - Message + Send + Refresh + CurrentUser + Logout -->
            <div class="row">
                <input type="text" placeholder="Napišite sporočilo ..." ID="Message" class="col-sm-8 message" runat="server"/>
                <asp:Button ID="Send" runat="server" Text="Pošlji" CssClass="col-sm-2 send" OnClick="Send_Click"/>
                <asp:Button ID="Refresh" runat="server" Text="Osveži" CssClass="col-sm-2 refresh" OnClick="Refresh_Click" />
                <asp:Label ID="CurrentUser" runat="server" Text="Prijavljeni ste kot: " CssClass="col-sm-10 currentuser"></asp:Label>
                <asp:Button ID="Logout" runat="server" Text="Odjava" CssClass="col-sm-2 logout" OnClick="Logout_Click" />
                <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionString %>" SelectCommand="SELECT [username], [besedilo] FROM [Pogovor]">
                </asp:SqlDataSource>
            </div><!-- third row - Message + Send + Refresh + CurrentUser + Logout -->

        </div> <!-- container -->
    </form>
</body>
</html>