# FROM scratch
# COPY hello /
# CMD ["/hello"]

FROM ubuntu AS build
RUN apt-get update && apt-get install -y build-essential
COPY hello.c /
RUN make hello
FROM gcr.io/distroless/cc
COPY --from=build /hello /hello
CMD ["/hello"]