apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hi
  name: hi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hi
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  minReadySeconds: 15
  template:
    metadata:
      labels:
        app: hi
        version: v3
    spec:
      containers:
      - image: hi:v3
        imagePullPolicy: IfNotPresent
        name: hi
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /live
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 5
      restartPolicy: Always
      terminationGracePeriodSeconds: 30